# General example

### Choose and download data

Select a combination of variables and fetch data from one day.

Resample to one measurement per 10s; filter for the Northern Hemisphere.

In [1]:
from viresclient import SwarmRequest
import datetime as dt

request = SwarmRequest()

request.set_collection("SW_OPER_MAGA_LR_1B")

request.set_products(measurements=["F","B_NEC"],
                     models=["MCO_SHA_2C", "MMA_SHA_2C-Primary", "MMA_SHA_2C-Secondary"],
                     auxiliaries=["QDLat", "QDLon"],
                     residuals=False,
                     sampling_step="PT10S")

request.set_range_filter(parameter="Latitude",
                         minimum=0,
                         maximum=90)

data = request.get_between(start_time=dt.datetime(2016,1,1),
                           end_time=dt.datetime(2016,1,2))

[1/1] Processing:  100%|██████████|  [ Elapsed: 00:01, Remaining: 00:00 ]
      Downloading: 100%|██████████|  [ Elapsed: 00:01, Remaining: 00:00 ] (0.766MB)


### Save the data directly

You can save the generated data file directly then open it using other software.

In [2]:
data.to_file('testfile.cdf')

Data written to testfile.cdf


### Convert to a pandas DataFrame

[pandas](https://pandas.pydata.org/pandas-docs/stable/overview.html) offers many useful features for working with 2D labelled time series data.

In [4]:
df = data.as_dataframe()
df.head()

Spacecraft  Latitude   Longitude      Radius           F  \
Timestamp                                                                      
2016-01-01 00:28:00          A  0.197610 -102.681841  6828390.60  24630.6312   
2016-01-01 00:28:10          A  0.838158 -102.693946  6828288.87  24808.1073   
2016-01-01 00:28:20          A  1.478724 -102.706041  6828186.32  24993.3709   
2016-01-01 00:28:30          A  2.119308 -102.718118  6828082.97  25186.2207   
2016-01-01 00:28:40          A  2.759911 -102.730169  6827978.83  25386.4755   

                     F_MCO_SHA_2C  F_MMA_SHA_2C-Primary  \
Timestamp                                                 
2016-01-01 00:28:00  24795.742996            127.134287   
2016-01-01 00:28:10  24971.853392            127.197315   
2016-01-01 00:28:20  25155.643730            127.257710   
2016-01-01 00:28:30  25346.943757            127.315462   
2016-01-01 00:28:40  25545.573072            127.370566   

                     F_MMA_SHA_2C-Secondary  \
Timestamp                                     
2016-01-01 00:28:00               33.517576   
2016-01-01 00:28:10               33.718966   
2016-01-01 00:28:20               33.932493   
2016-01-01 00:28:30               34.157878   
2016-01-01 00:28:40               34.394821   

                                                                 B_NEC  \
Timestamp                                                                
2016-01-01 00:28:00        [23432.3208, 2928.6274000000003, 7000.6948]   
2016-01-01 00:28:10                  [23451.1801, 2899.534, 7554.4035]   
2016-01-01 00:28:20  [23465.812100000003, 2871.8025000000002, 8109....   
2016-01-01 00:28:30                 [23476.3596, 2844.1066, 8666.6296]   
2016-01-01 00:28:40                 [23482.5073, 2817.0387, 9225.1501]   

                                                      B_NEC_MCO_SHA_2C  \
Timestamp                                                                
2016-01-01 00:28:00  [23604.765693069177, 2930.2688321265728, 7004....   
2016-01-01 00:28:10  [23623.327008268625, 2901.392633804825, 7557.3...   
2016-01-01 00:28:20  [23637.6657342565, 2873.1207904780367, 8112.48...   
2016-01-01 00:28:30  [23647.710917671076, 2845.447078036548, 8669.2...   
2016-01-01 00:28:40  [23653.3949273992, 2818.3663458182045, 9227.67...   

                                              B_NEC_MMA_SHA_2C-Primary  \
Timestamp                                                                
2016-01-01 00:28:00  [-125.78890509740265, -5.302191425378982, 17.6...   
2016-01-01 00:28:10  [-125.60166979171441, -5.252627485291866, 19.3...   
2016-01-01 00:28:20  [-125.38835978948227, -5.203014637815361, 21.1...   
2016-01-01 00:28:30  [-125.14900320901313, -5.153357531132542, 22.8...   
2016-01-01 00:28:40  [-124.88363654458195, -5.103660714780139, 24.5...   

                                            B_NEC_MMA_SHA_2C-Secondary  \
Timestamp                                                                
2016-01-01 00:28:00  [-32.5031562033331, -1.386212193226803, -8.065...   
2016-01-01 00:28:10  [-32.494418615582255, -1.3566476193699097, -8....   
2016-01-01 00:28:20  [-32.47777846302375, -1.3273711242288924, -9.7...   
2016-01-01 00:28:30  [-32.45318157347463, -1.2983807863969918, -10....   
2016-01-01 00:28:40  [-32.42057710492788, -1.2696744882122784, -11....   

                         QDLat      QDLon  
Timestamp                                  
2016-01-01 00:28:00   8.425159 -30.812750  
2016-01-01 00:28:10   9.068963 -30.902256  
2016-01-01 00:28:20   9.713511 -30.990784  
2016-01-01 00:28:30  10.358768 -31.078363  
2016-01-01 00:28:40  11.004701 -31.165012

#### Extract numpy arrays

Individual entries (rows) in multi-dimensional variables (e.g. B_NEC) are currently stored as lists so they need to be as extracted as arrays to do array operations. This behaviour will likely change in the future to provide "flat" dataframes instead (i.e. the B_NEC column expanded as three columns: B_N, B_E, B_C, etc)

In [5]:
import numpy as np

B_NEC = np.stack(df['B_NEC'].values)
X,Y,Z = (B_NEC[:,i] for i in (0,1,2))
X,Y,Z

(array([23432.3208, 23451.1801, 23465.8121, ..., 19454.4269, 19271.3803,
        19084.199 ]),
 array([2928.6274, 2899.534 , 2871.8025, ...,  824.8021,  808.9134,
         792.9848]),
 array([ 7000.6948,  7554.4035,  8109.7535, ..., 32624.9088, 33094.2485,
        33559.0953]))

Pandas dataframes are not so good when we have higher-dimensional data, hence the motivation to use xarray: <http://xarray.pydata.org/en/stable/faq.html#why-is-pandas-not-enough>

### Convert to an xarray Dataset

[xarray](http://xarray.pydata.org/en/stable/) extends the power of pandas to N-dimensional data but is more complex to work with.

In [6]:
ds = data.as_xarray()
ds

<xarray.Dataset>
Dimensions:                     (Timestamp: 4256, dim: 3)
Coordinates:
  * Timestamp                   (Timestamp) datetime64[ns] 2016-01-01T00:28:00 ... 2016-01-01T23:59:50
Dimensions without coordinates: dim
Data variables:
    Spacecraft                  (Timestamp) <U1 'A' 'A' 'A' 'A' ... 'A' 'A' 'A'
    Latitude                    (Timestamp) float64 0.1976 0.8382 ... 30.46 31.1
    Longitude                   (Timestamp) float64 -102.7 -102.7 ... -95.37
    Radius                      (Timestamp) float64 6.828e+06 ... 6.823e+06
    F                           (Timestamp) float64 2.463e+04 ... 3.861e+04
    F_MCO_SHA_2C                (Timestamp) float64 2.48e+04 ... 3.861e+04
    F_MMA_SHA_2C-Primary        (Timestamp) float64 127.1 127.2 ... 43.23 43.24
    F_MMA_SHA_2C-Secondary      (Timestamp) float64 33.52 33.72 ... 4.576 4.604
    B_NEC                       (Timestamp, dim) float64 2.343e+04 ... 3.356e+04
    B_NEC_MCO_SHA_2C            (Timestamp, dim) fl

Extracting numpy arrays from xarray:

In [7]:
X,Y,Z = (ds["B_NEC"][:,i].values for i in (0,1,2))
X,Y,Z

(array([23432.3208, 23451.1801, 23465.8121, ..., 19454.4269, 19271.3803,
        19084.199 ]),
 array([2928.6274, 2899.534 , 2871.8025, ...,  824.8021,  808.9134,
         792.9848]),
 array([ 7000.6948,  7554.4035,  8109.7535, ..., 32624.9088, 33094.2485,
        33559.0953]))

### Work on xarray objects directly

Calculate the custom residual $B_{res} = B_{obs} - B_{MCO} - B_{MMA}$ and plot the Z component against time

In [8]:
B_res = ds["B_NEC"] - ds["B_NEC_MCO_SHA_2C"]\
                    - ds["B_NEC_MMA_SHA_2C-Primary"]\
                    - ds["B_NEC_MMA_SHA_2C-Secondary"]
B_res

<xarray.DataArray (Timestamp: 4256, dim: 3)>
array([[-14.152832,   5.046971, -13.00904 ],
       [-14.05082 ,   4.750641, -13.44751 ],
       [-13.987496,   5.212095, -14.088606],
       ...,
       [ -0.065038,  -2.56282 ,  -3.695835],
       [  0.583051,  -3.247   ,  -4.246418],
       [  1.325767,  -4.054801,  -4.315355]])
Coordinates:
  * Timestamp  (Timestamp) datetime64[ns] 2016-01-01T00:28:00 ... 2016-01-01T23:59:50
Dimensions without coordinates: dim

In [ ]:
%matplotlib inline
B_res[:,2].plot(x='Timestamp');